---
- hosts: mon2
  remote_user: root
  vars_files:
    - var.yaml

  tasks:
    - name: deploy_mon_folder1
      copy: src=/etc/ceph dest=/etc
    - name: deploy_mon_folder2
      copy: src=/var/lib/ceph dest=/var/lib

    - name: deploy_mon_node
      shell: docker run -d --net=host --name=mon --restart=always -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -e MON_IP={{ansible_all_ipv4_addresses[0]}} -e CEPH_PUBLIC_NETWORK={{net}} ceph/daemon mon 
