---
- hosts: ceph
  remote_user: root
  vars_files:
    - var.yaml

  tasks:
    - name: deploy_osd_node
      shell: docker run -d --net=host --name={{item}} --restart=always --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -v /dev/:/dev/ -e OSD_FORCE_ZAP=1 -e OSD_DEVICE=/dev/{{item}} -e OSD_TYPE=disk -e OSD_BLUESTORE=1 ceph/daemon osd
      with_items:
        - "{{osd}}"
